language: perl

sudo: false

perl:
    - "5.26"

install:
    - "cpanm --quiet --notest Bio::Perl"
    - "wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.7.1/ncbi-blast-2.7.1+-x64-linux.tar.gz"
    - "tar zxvf ncbi-blast-2.7.1+-x64-linux.tar.gz"
    - "export PATH=$PWD/bin:$PWD/ncbi-blast-2.7.1+/bin:$PATH"

script:
    - "berokka --version"
    - "berokka --help"
    - "! berokka --doesnotexist"
    - "berokka --check"
    - "berokka --test"
